<HTML>
<HEAD>
<TITLE>APC GUI</TITLE>
<FRAMESET ROWS=100,* BORDER=0>
  <FRAME SRC=top.php SCROLLING=no RESIZE=no NAME=top>
  <FRAME SRC=hosts.php NAME=main>
</FRAMESET>
</HEAD>
<BODY>
<NOFRAMES>
APC GUI NEEDS FRAMES
</NOFRAMES>
</BODY>
</HTML>
